discord_server_id:
  default: 555077426137268234
  description: |
    The server ID to be embeded.

sidebar_side: 
  default: right
  type: enum
  choices: 
    - left
    - right

stick_on_scroll: 
  default: true
  description: |
    When checked sidebar has a sticky position on scroll